### PR TITLE
Align place categories schema with names, and add category name validation

### PR DESCRIPTION
**Pull request by vcschapp**
# Description

*Brief description of the business purpose and effect of the pull request.*

This PR contains two changes.

1. It renames the `place` feature's `categories.main` property to `categories.primary` to align it with the names schema, which uses `names.primary`.
    - Either `main` or `primary` would be fine; `primary` was chosen because it causes fewer touchpoints, since changing the names schema requires touching five themes' data generation pipelines.
    - An issue has been filed with the Places theme to fix the data generation pipeline to align with the schema before the July release.
3. It adds JSON Schema validation to the `place` feature's category names. Note that this change reveals some invalid category names in the places category CSV file and dataset and required me to file a bug issue to places to fix it.

# Reference

*List of relevant links to GitHub issues, PRs, and other documentation.*

1. Bug issue for Places TF to fix category names: https://github.com/OvertureMaps/tf-place-data/issues/135
4. Issue for Places TF to ensure `categories.main` is renamed to `categories.primary` in the data.

# Testing

*Brief description of the testing done for this change showing why you are confident it works as expected and does not introduce regressions. Provide sample output data where appropriate.* 

- Updated examples and counterexamples.
- Added a new counterexample for the category name validation.
- Ran the tests.

# Checklist

*Checklist of tasks commonly-associated with schema pull requests. Please review the relevant checklists and ensure you do all the tasks that are required for the change you made.*

1. [X] ~~Add~~ Update relevant examples.
2. [X] Add relevant counterexamples.
3. [X] Update any counterexamples that became obsolete. For example, if a counterexample uses property `A` but is not intended to test property `A`'s validity, and you made a schema change that invalidates property `A` in that counterexample, fix the counterexample to align it with your schema change.  
4. [ ] Update in-schema documentation using plain English written in complete sentences, if an update is required.
5. [ ] Update Docusaurus documentation, if an update is required.
6. [ ] Review change with Overture technical writer to ensure any advanced documentation needs will be taken care of, unless the change is trivial and would not affect the documentation.

# Documentation Website

*Update the hyperlink below to put the pull request number in.*

[Docs preview for this PR.](https://dfhx9f55j8eg5.cloudfront.net/pr/216)

### CODE REVIEW

**Review by jwass — APPROVED** [review]

**Review by DavidKarlas — APPROVED** [review]

**Review by Dritte — APPROVED** [review]
I'm aligned on this. It makes sense to bring this in line with the other layers, and no better time than the present to make such a change, particularly before GA.

**Comment by vcschapp** [comment]
> I'm aligned on this. It makes sense to bring this in line with the other layers, and no better time than the present to make such a change, particularly before GA.

Awesome. Thanks Bobby!

**Comment by vcschapp** [comment]
@TristanDiet-TomTom indicates that @JanCallewaert-TomTom wants to bring this up for discussion in the Places TF meeting on Thursday, hence still waiting on a sign-off from TomTom.

**Comment by jlockfb** [comment]
Discussed during Thursday task force meeting. We'll go ahead with the suggested changes.

**Review by TristanDiet-TomTom — APPROVED** [review]

**Pull request merged**
