### PR TITLE
Adding elevation to base

### PR DESCRIPTION
**Pull request by jenningsanderson**
Adds elevation as a top-level attribute in `land`, `landUse`, and `water` types.

### CODE REVIEW

**Review by BoZivk — APPROVED** [review]

**Comment by ImreSamu** [comment]
Non-blocking comment

> "description: Elevation **above sea level (in meters)** of the feature."

Is a negative value expected here? 
Or will that be in a different field? --> "below sea level"

https://en.wikipedia.org/wiki/List_of_places_on_land_with_elevations_below_sea_level

**Review by jwass — COMMENTED** [review]
Does elevation only apply to some types? I think it was mountain summits or things like that where it makes sense but should this be able to go on anything?

**Comment by vcschapp** [comment]
> Does elevation only apply to some types? I think it was mountain summits or things like that where it makes sense but should this be able to go on anything?

Good question, I have the same one.

**Review by DavidKarlas — APPROVED** [review]

**Comment by vcschapp** [comment]
In Schema TF [2024-01-31](https://github.com/OvertureMaps/schema-wg/issues/261), we agreed that this PR would be merged but that a bug would be entered to ensure that the `elevation` property is restricted to only those features types/sub-types for which it makes sense.

**Comment by vcschapp** [comment]
Created a new issue and assigned it to @jenningsanderson : https://github.com/OvertureMaps/schema-wg/issues/263

**Review by vcschapp — APPROVED** [review]
Approved with the caveats discussed in Schema TF [2024-01-31](https://github.com/OvertureMaps/schema-wg/issues/261).

**Pull request merged**
