### PR TITLE
Renaming division `boundary` type name to `division_boundary`

### PR DESCRIPTION
**Pull request by DavidKarlas**
# Description

@danabauer brought up issue that `boundary` is very generic and might conflict with other themes in future.

# Reference

*List of relevant links to GitHub issues, PRs, and other documentation.*

1. https://github.com/OvertureMaps/tf-admin/issues/74

# Testing

*Brief description of the testing done for this change showing why you are confident it works as expected and does not introduce regressions. Provide sample output data where appropriate.* 

Ran test.sh.

# Checklist

*Checklist of tasks commonly-associated with schema pull requests. Please review the relevant checklists and ensure you do all the tasks that are required for the change you made.*

1. [ ] Add relevant examples.
2. [ ] Add relevant counterexamples.
3. [ ] Update any counterexamples that became obsolete. For example, if a counterexample uses property `A` but is not intended to test property `A`'s validity, and you made a schema change that invalidates property `A` in that counterexample, fix the counterexample to align it with your schema change.  
4. [ ] Update in-schema documentation using plain English written in complete sentences, if an update is required.
5. [ ] Update Docusaurus documentation, if an update is required.
6. [ ] Review change with Overture technical writer to ensure any advanced documentation needs will be taken care of, unless the change is trivial and would not affect the documentation.

# Documentation Website

*Update the hyperlink below to put the pull request number in.*

[Docs preview for this PR.](https://dfhx9f55j8eg5.cloudfront.net/pr/213

### CODE REVIEW

**Comment by vcschapp** [comment]
Meeting where this was discussed: https://github.com/OvertureMaps/tf-admin/issues/86

**Review by jwass — APPROVED** [review]

**Review by jenningsanderson — APPROVED** [review]
👍

**Review by jenningsanderson — CHANGES_REQUESTED** [review]
Need to update docusaurus/docs/schema/reference/divisions/boundary.mdx to docusaurus/docs/schema/reference/divisions/division_boundary.mdx


Exhaustive list of all broken links found:
  - Broken link on source page path = /pr/213/schema/reference/divisions/division_area/:
     -> linking to /pr/213/schema/reference/divisions/division_boundary/
  - Broken link on source page path = /pr/213/schema/reference/divisions/division/:
     -> linking to /pr/213/schema/reference/divisions/division_boundary/

**Comment by vcschapp** [comment]
> Need to update docusaurus/docs/schema/reference/divisions/boundary.mdx to docusaurus/docs/schema/reference/divisions/division_boundary.mdx
> 
> Exhaustive list of all broken links found:
> 
> * Broken link on source page path = /pr/213/schema/reference/divisions/division_area/:
>   -> linking to /pr/213/schema/reference/divisions/division_boundary/
> * Broken link on source page path = /pr/213/schema/reference/divisions/division/:
>   -> linking to /pr/213/schema/reference/divisions/division_boundary/

@DavidKarlas Can you fix this and update the PR?

**Comment by DavidKarlas** [comment]
@jenningsanderson fixed, tnx! After latest update of `jv` version, I have problem running it locally :(

**Review by jenningsanderson — DISMISSED** [review]

**Comment by vcschapp** [comment]
> @jenningsanderson fixed, tnx! After latest update of `jv` version, I have problem running it locally :(

Thanks @DavidKarlas. I unfortunately gave you some sparkly new merge conflicts ✨ due to another recent merge. Think you can clear the conflicts so we can get this PR shipped?

**Comment by DavidKarlas** [comment]
Rebased on latest `dev` after https://github.com/OvertureMaps/schema/pull/215 was merged, which caused conflicts

**Comment by DavidKarlas** [comment]
Rebased again was conflicting with removal of admins

**Review by vcschapp — APPROVED** [review]

**Review by jenningsanderson — APPROVED** [review]

**Review by jwass — APPROVED** [review]

**Review by TristanDiet-TomTom — APPROVED** [review]

**Pull request merged**
