### PR TITLE
Formalize Opening Hours

### PR DESCRIPTION
**Pull request by jenningsanderson**
Addresses: 

- https://github.com/OvertureMaps/schema-wg/issues/203

### CODE REVIEW

**Comment by jenningsanderson** [comment]
@AleksandraDebicka-TomTom I'm not sure what more needs to happen here?

**Review by vcschapp — CHANGES_REQUESTED** [review]
Is it possible update the PR so it's a clean diff with just the one relevant commit?

Currently this PR is pulling in 19 commits, but I think the only one you want in the PR is this one: https://github.com/OvertureMaps/schema/pull/84/commits/982aa6ec28e6e2b846a02d711fa508071d45a0e3

Should be possible to make a clean branch from a local copy of `origin/dev` and just pull that one commit onto the branch, force push, and update the PR...

**Review by jwass — COMMENTED** [review]
Makes sense to me. 

Is there a plan for non-JSON schema validation?

**Review by jwass — APPROVED** [review]

**Review by vcschapp — APPROVED** [review]
```
                               |\
                               ||.
                               ||;`
                             ,'|;  :
                           ,': |;  `
                         ,'  | ;  `-`
                       ,'    | ;     :
                     ,'    `-|;      `
                    ;        ;        `
                  ,'      `--\`-.   `--:
            ,-._,'`.         |\||`-.   `
            `;-.`-._`.       | |\ \ `-. `
             :`--`-.`-\  `--.| /`\;\   `-:
             ;      ``-`.    |/  ;  \    `.
             ;           `.`-/   ;   \    `
             ;      :      `/    ;    \    `
     ,-._    |             /     ;   -`\    :
     `;-.`-._| :          /      |      \   `
      ;   `-.|     :     /       |       \   `
      ;      | :    :   /        |        \   :
      ;      | :       /   ;     |         \  `
      ;      |        /   ;      |       --`\  `
      |      |  :    /    ;      |           \  :
      | :    |  :   /            ;            \ `
      |      :     ;            ;:'-.._      -`\ `
      |  :   ;___  ;'---....___;__:__| `-._     \ :
      |      :   `;``-------'';||  :  \    `-._  \`
     -=======:===;===========;=||   :  \       `-.\:
         ___ ; _;_||        ;  ||___,:-.\___,....__\_
        |`--:.|;_o||-______;,..-----""""" __|__...-''
----....|___     """"                 jrei__||-------........________
            """"----....____      __..--''  || ~~~~~
     ~~~ ~~~                """"----....____|/    ~~~~~~~     ~~~~~~~
~~~                ~~~~   ~~~~~~  ~  ~~~       ~~~~
  ~~~~~      ~~~      ~     ~~~~~~~~~ ~~~                ~~~~~~~~~~
```

**Pull request merged**
